### ISSUE TITLE
Understanding the underlying mathematical idea

### ISSUE THREAD

**Issue by white07S** [white07S/Fibonacci-Retracement#10]
Considering the basic knowledge of support and resistance, I would like to introduce the underlying mathematical idea.

1. Finding global maxima and minima in a time series data
2. After obtaining the pivot points, choosing two of them would be simple because any pair of minima or maxima points would form a line, creating a total of n(n-1) complete lines, all of which are perfect fitting lines because basic geometry states that 2 distinct points can describe a line. However, there are n(n-1)(n-2) methods to choose 3 points, and this enumeration has an algorithmic complexity of O(n3). There will be some mistakes because these points are not always in a straight line. Since we must exclude wrong point sets and include correct ones, the error level will be crucial.
3. Few things to read:

- https://en.wikipedia.org/wiki/Numerical_differentiation
- [Library for Numerical differentiation] https://github.com/maroba/findiff
- [Alternative for line finding algorithm] https://en.wikipedia.org/wiki/Hough_transform

Drop down a comment in case of any doubt.

**Comment by lukik45** [comment]
@white07S what do you mean by pivot points? https://www.investopedia.com/terms/p/pivotpoint.asp

**Comment by lukik45** [comment]
@bujowskis I found a neat explanation of **Hough transform**
https://www.youtube.com/watch?v=XRBc_xkZREg

**Comment by bujowskis** [comment]
thanks @lukik45, didn't sit down to it yet but will definitely check it out

**Comment by white07S** [comment]
> @white07S Is that what you mean by pivot points? https://www.investopedia.com/terms/p/pivotpoint.asp ?
> 

> Yeah that's exactly what I meant.

**Comment by bujowskis** [comment]
Okay, after a few days of getting the hang of it, I think it's to some degree clear. I think I may be missing something regarding the application of the Hough transform, but I can't really formulate what it is, so I think it's best if we keep going and if it arises, I'll ask you two

**Comment by bujowskis** [comment]
I think there's nothing else to add on here, so I'm closing the issue
