### ISSUE TITLE
Data split

### ISSUE THREAD

**Issue by bujowskis** [white07S/Fibonacci-Retracement#11]
Notes:
- keep in mind the restrictions on the data interval-duration (check external python
- `10y`: 1d
- `6m`: 1h
- `1m`: 15min

Start-end dates:
- start date (i.e. end date of the train interval) - `04.10.2022` (the day of initial commit)

- [x] fill the above
- [x] fix start-end dates of the data split
- [x] prepare data split for one stock

- [x] `fixme` - trader holidays

**Comment by bujowskis** [comment]
forgot to mention
- 15min interval has duration restriction up to 60 days, so for now I'm working on 1month of 15min
- 30min interval has the same duration restrictions as 15min, so I've increased it to 1h

**Comment by bujowskis** [comment]
I've added the "naive" puller, but it needs rework - note the `fixme` in `datasplit.py`

**Comment by bujowskis** [comment]
added the remaining two `fixme`

**Comment by white07S** [comment]
After understanding the module of the B/S model it doesn't make sense to train a model based on a time frame rather than we should train a model based on categorized stocks.

**Comment by bujowskis** [comment]
is the trader holiday problem solved then? I've seen you @white07S add some trader calendar there

**Comment by white07S** [comment]
Yeah, it's solved and you can close this issue that trader calendar is specifically for stock data to provide accurate data in matplotlib tick module to make it understandable.

Regarding training and testing, we will be splitting stock based on categorization.

**Comment by bujowskis** [comment]
can you elaborate how this split will work?

**Comment by bujowskis** [comment]
From our talk, the split is as follows:
- no longer based on time, but on `volume`
- divide stocks into categories
  - `large` volume
  - `mid` volume
  - `small` volume
- some stocks from each category are used for test and validate, the rest is train
- `note` - 3 models are trained

**Comment by bujowskis** [comment]
moved the remaining things that are irrelevant to this issue per se to their own issues, this one seems to be done
