### ISSUE TITLE
OOP polymorphism (for 3 different Sup-Res-Fib calculations code)

### ISSUE THREAD

**Issue by bujowskis** [white07S/Fibonacci-Retracement#19]
basically some common sort of interface all three methods will share to simplify the usage

**Comment by bujowskis** [comment]
this is preliminary to the rework of Calculation codes, need the fundamental components to figure out the right OOP patterns (among which, polymorphism)

**Comment by lukik45** [comment]
@bujowskis I added a [branch](https://github.com/white07S/Fibonacci-Retracement/tree/lukasz-sup-res-review) that targets that issue.

**Comment by bujowskis** [comment]
I'm moving it to `in review`, seems some good stuff done there, it may have already done the trick

**Comment by bujowskis** [comment]
I need to review it, but unfortunately no sooner than next weekend

**Comment by bujowskis** [comment]
decided it's fine as-it-is, moved on to other tasks
