### ISSUE TITLE
Mid-term presentation

### ISSUE THREAD

**Issue by bujowskis** [white07S/Fibonacci-Retracement#20]
- use the provided template
- keep it **simple** and **easily understandable** - *recall the **Feynman technique***
  - for `Motivation` - goal in simple terms

Submission deadline - `26.11.2022` `!!!`

**Comment by lukik45** [comment]
I've created the slides
[https://docs.google.com/presentation/d/1PSp80UKocYdPu4K9bPf4b-EJONgjh8in63nI0HCNfy8/edit?usp=sharing](url)
I'll try to include all the necessary stuff for the presentation and then ask you for the review

**Comment by lukik45** [comment]
I don't know where to put the information about the mathematical proof for the accuracy of support and resistance, and whether to add it at all. @white07S?

**Comment by white07S** [comment]
> I don't know where to put the information about the mathematical proof for the accuracy of support and resistance, and whether to add it at all. @white07S?

I would say we should put it for final round submission.

**Comment by bujowskis** [comment]
@lukik45 can you add me and @white07S as editors to the presentation and make `anyone with link` a Viewer instead of Editor?

**Comment by bujowskis** [comment]
I've put whatever the content I could, waiting for @lukik45 to review
