### ISSUE TITLE
Add documentation and references to the Calculations code

### ISSUE THREAD

**Issue by bujowskis** [white07S/Fibonacci-Retracement#25]
- [x] find and add the materials (in general + code)
- [x] let us know
- [x] @white07S add high-level explanations and relevant, "explicit" links (`codeReview/sup_res`, etc. - it's nice to keep it throughout the whole project)

**Comment by bujowskis** [comment]
@white07S is [this commit](https://github.com/white07S/Fibonacci-Retracement/commit/298e8413630c1b4307d03a6d9ae8b771f0149dde) the explanations?

**Comment by white07S** [comment]
@bujowskis Indded [this commit](https://github.com/white07S/Fibonacci-Retracement/commit/298e8413630c1b4307d03a6d9ae8b771f0149dde) is the explanations for those calculations.

I am not sure why Cython automatically created that file but I will try to fix it asap.

**Comment by bujowskis** [comment]
@white07S I mean, I'm not sure if there's anything wrong they are being created, the question is - should cython be committed?

**Comment by bujowskis** [comment]
@white07S also, there seem to have risen some errors with the imports/structure and the tests are failing?
