### ISSUE TITLE
Decide the journal

### ISSUE THREAD

**Issue by bujowskis** [white07S/Fibonacci-Retracement#26]
- [x] add the options w. exemplary papers - [look at this commit](https://github.com/white07S/Fibonacci-Retracement/commit/b573df912c253afd7c62039b7c3ce79283fe2d2b)
  - [x] narrowed financial journals (3 opts)
  - [x] more general (for some options)
- [x] read those
- [x] decide

**Comment by bujowskis** [comment]
From my reading into these

Financial-specific
- Journal of Financial and Quantitative Analysis (JFQA)
  - submission fee is $350
  - extremely competitive, 8% approval
- RISK
  - https://www.risk.net/journal-of-risk <- is this the proper link?
  - I'm not sure our project fits nicely into risk management precisely

Other
- SSRN - either https://www.ssrn.com/index.cfm/en/ern/ or https://www.ssrn.com/index.cfm/en/fen/
- ARXIV - https://arxiv.org/ - we seem to fit nicely
- https://events.risk.net/quantsummiteurope - this the link to quant summit?

**Comment by bujowskis** [comment]
@white07S it'd be most helpful if you checked the boxes and let us know here, in the project, besides just committing it in a file into the code.

Also, make sure to include the links and references. There is some overlap between the papers, we may end up not on the same page.

**Comment by white07S** [comment]
Alright, I am sorry for that, I will keep it in mind.

**Comment by bujowskis** [comment]
Go for `JFQA`
