### ISSUE TITLE
Add financial data

### ISSUE THREAD

**Issue by bujowskis** [white07S/Fibonacci-Retracement#6]
- [x] clean the data
- [x] add

**Comment by bujowskis** [comment]
What about cleaning? Sharing the same working data copy sounds better cleaning-wise

**Comment by white07S** [comment]
tbh there is no need to clean the data because our source is already providing cleaned data

**Comment by bujowskis** [comment]
I'm marking `clean the data` checkbox then, omw to review

**Comment by bujowskis** [comment]
@white07S I think `requirements.txt` doesn't cover the requirements for downloading the external data. Is that by design?

**Comment by bujowskis** [comment]
okay, so from a phone talk
- `requirements.txt` is not supposed to cover the downloading data scripts (if it turns out otherwise, we add the requirements)
- after some refactoring and adding the `__main__` I was able to download the data, no issues (see `exemplary-external.csv)
- I've added some `todo`'s, but they're not of that big priority at this point and we may add them later

The build is passing (since no inference in the tests), LGTM
