### ISSUE TITLE
Read Survival Analysis materials

### ISSUE THREAD

**Issue by bujowskis** [white07S/Fibonacci-Retracement#8]
- [x] Read the papers
- [x] Make notes
- [ ] Meet up to clarify concerns

**Comment by lukik45** [comment]
@white07S should we just familiarise ourselves with these two links, or sth more?
https://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/BS704_Survival/BS704_Survival6.html
https://square.github.io/pysurvival/

**Comment by white07S** [comment]
> @white07S should we just familiarise ourselves with these two links, or sth more?
> https://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/BS704_Survival/BS704_Survival6.html
> https://square.github.io/pysurvival/

> Understanding the underlying ideas presented in this two links are enough, there are some different models like COX, I would suggest to get an overview of this model.

**Comment by white07S** [comment]
- [ ] Only understand the underlying idea of the COX model

**Comment by bujowskis** [comment]
So I went through the materials and there are two concerns I have to raise, both regarding [this article](https://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/BS704_Survival/BS704_Survival6.html)

> (...) There are several important **assumptions for the appropriate use of Cox proportional hazards regression model**

> **Independence** of survival times between distinct individuals in the sample

In our case, are the stocks independent for the appropriate use of Cox? Still unsure whether to think of *distinct individuals* as multiple stocks or some points within a given stock, but in both cases think of the following:
- `stock on stock` - impact analysis and correlations
- `within a stock` - trends, sentiment analysis, etc.

> Constant hazard ratio over time

Is it going to be constant and fulfil that assumption?

**Comment by white07S** [comment]
Yes it is enough but considering COX have its own assumptions, we need to derive our own assumptions while modelling our model

**Comment by bujowskis** [comment]
is it going to affect anything we have to do before paper proof and model? The coding parts? @white07S? Otherwise, it'd be more appropriate to start a new `Todo` issue and make deriving our assumptions a checkbox in it

**Comment by white07S** [comment]
Yeah, that's a great idea.
